#!/bin/sh -e
#
# Works around missing origin branches when unshallowing a repo
# `git fetch --unshallow` should be enough but it has this ^ issue.

# TODO: make sure it's executed from the root of the repo

if ! [ -f .git/shallow ]; then
  echo "Repo already unshallow"
  exit
fi

repo=$(git remote -v | grep origin | head -n1 | awk '{ print $2 }')
echo "Restoring $repo"
git remote rm origin
git remote add origin "$repo"
echo "Fetching origin"
git fetch origin
